Bugfix/LTK-20031-device-is-accepting-the-fw-signature-corrupted-image…
etn-ccis/mcuboot pull request #13
Opened 2023-10-04 11:26 UTC by PragatiGarg-eaton

…-and-updating-the-fw:

- Firmware signature is getting added twice in the codepack/signed binary after signing the image. If we corrupt the signature at the duplicated location, FUS was successful (which makes sense too).
- Removed the redundant tlv.add function call and added UsageError message instead (referred from latest https://github.com/mcu-tools/mcuboot/blob/main/scripts/imgtool/image.py)

2023-10-04 11:36 UTC, SadanandPenore-eaton commented on scripts/imgtool/image.py
> +                raise click.UsageError("Can not sign using key and provide fixed-signature at the same time")
Hi @PragatiGarg-eaton , The fix was supposed to in firmware right.
Whatever wrong the code the device should not accept, right? So for the wrong image the firmware should reject it.

2023-10-04 12:57 UTC, VineetaNarkhede-eaton requested changes

2023-10-04 13:08 UTC, VineetaNarkhede-eaton approved these changes

2023-10-04 13:12 UTC, PragatiGarg-eaton commented on scripts/imgtool/image.py
> +                raise click.UsageError("Can not sign using key and provide fixed-signature at the same time")
Image.py utility was adding firmware signatures twice in the signed binary. And, while corrupting the signature at the duplicated or wrong location, FUS was successful. So, if we corrupt the signature on the right location, where the signature resides, fus is not as successful which as expected. 
Hence, removed the redundant addition from the mcuboot which was creating the duplicate signatures.

2023-10-04 16:02 UTC, SadanandPenore-eaton commented on scripts/imgtool/image.py
> +                raise click.UsageError("Can not sign using key and provide fixed-signature at the same time")
Call for the innersource in MCUBOOT?

2023-10-04 16:02 UTC, SadanandPenore-eaton approved these changes

2023-10-05 04:27 UTC, prayassamriya commented on scripts/imgtool/image.py
>          else:
where are these 2 lines gone?

2023-10-05 05:21 UTC, PragatiGarg-eaton commented on scripts/imgtool/image.py
>          else:
Took a reference from the latest Zephyr 3.4 file: https://github.com/mcu-tools/mcuboot/blob/main/scripts/imgtool/image.py
However, these changes were made long back in 2022: https://github.com/mcu-tools/mcuboot/commit/160303c202ade15b8d736094a6d616f63b309153
![image](https://github.com/etn-ccis/mcuboot/assets/107679628/e0ff1568-fbf4-4f45-9ebf-3475f721b8b7)

2023-10-05 11:08 UTC, PragatiGarg-eaton commented on scripts/imgtool/image.py
> +                raise click.UsageError("Can not sign using key and provide fixed-signature at the same time")
Whole cert-based code signing solution is pending to be inner-sourced. ( contributed )...

2023-10-05 11:09 UTC, merged